export const dummyUsers = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    skills: ["Dog Walking", "Cleaning"],
    availability: ["2025-07-20", "2025-07-22"],
    zip: "77001",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    skills: ["Animal Care"],
    availability: ["2025-07-21"],
    zip: "77002",
  },
  {
    id: 3,
    name: "Carla Ruiz",
    email: "carla@example.com",
    skills: ["Medical Assistance", "Cat Handling"],
    availability: ["2025-07-23", "2025-07-24"],
    zip: "77003",
  },
  {
    id: 4,
    name: "Daniel Lee",
    email: "daniel@example.com",
    skills: ["Cleaning", "Dog Walking", "Animal Care"],
    availability: ["2025-07-20", "2025-07-25"],
    zip: "77004",
  },
];

export const dummyEvents = [
  {
    id: 1,
    name: "Walk Dogs",
    description: "Help walk dogs in the shelter",
    location: "Main Shelter",
    requiredSkills: ["Dog Walking"],
    urgency: "High",
    date: "2025-07-20",
  },
  {
    id: 2,
    name: "Clean Cages",
    description: "Sanitize and clean animal cages",
    location: "Secondary Shelter",
    requiredSkills: ["Cleaning"],
    urgency: "Low",
    date: "2025-07-22",
  },
  {
    id: 3,
    name: "Vet Checkups",
    description: "Assist the vet with checkups",
    location: "Vet Room A",
    requiredSkills: ["Medical Assistance"],
    urgency: "Medium",
    date: "2025-07-23",
  },
  {
    id: 4,
    name: "Adoption Fair",
    description: "Help set up and run the adoption event",
    location: "Community Park",
    requiredSkills: ["Animal Care"],
    urgency: "High",
    date: "2025-07-21",
  },
  {
    id: 5,
    name: "Cat Playtime",
    description: "Supervised play session with cats",
    location: "Cat Lounge",
    requiredSkills: ["Cat Handling"],
    urgency: "Low",
    date: "2025-07-24",
  },
];

export const dummyMatches = [
  {
    volunteerName: "Alice Johnson",
    event: "Walk Dogs",
    skills: ["Dog Walking"],
    urgency: "High",
  },
  {
    volunteerName: "Alice Johnson",
    event: "Clean Cages",
    skills: ["Cleaning"],
    urgency: "Low",
  },
  {
    volunteerName: "Bob Smith",
    event: "Adoption Fair",
    skills: ["Animal Care"],
    urgency: "High",
  },
  {
    volunteerName: "Carla Ruiz",
    event: "Vet Checkups",
    skills: ["Medical Assistance"],
    urgency: "Medium",
  },
  {
    volunteerName: "Carla Ruiz",
    event: "Cat Playtime",
    skills: ["Cat Handling"],
    urgency: "Low",
  },
  {
    volunteerName: "Daniel Lee",
    event: "Clean Cages",
    skills: ["Cleaning"],
    urgency: "Low",
  },
];

export const dummyVolunteerHistory = [
  {
    volunteer: "Alice Johnson",
    event: "Walk Dogs",
    location: "Main Shelter",
    urgency: "High",
    skillsUsed: ["Dog Walking"],
    date: "2025-07-20",
    status: "Completed",
  },
  {
    volunteer: "Alice Johnson",
    event: "Clean Cages",
    location: "Secondary Shelter",
    urgency: "Low",
    skillsUsed: ["Cleaning"],
    date: "2025-07-22",
    status: "Upcoming",
  },
  {
    volunteer: "Bob Smith",
    event: "Adoption Fair",
    location: "Community Park",
    urgency: "High",
    skillsUsed: ["Animal Care"],
    date: "2025-07-21",
    status: "Completed",
  },
  {
    volunteer: "Carla Ruiz",
    event: "Vet Checkups",
    location: "Vet Room A",
    urgency: "Medium",
    skillsUsed: ["Medical Assistance"],
    date: "2025-07-23",
    status: "Upcoming",
  },
  {
    volunteer: "Carla Ruiz",
    event: "Cat Playtime",
    location: "Cat Lounge",
    urgency: "Low",
    skillsUsed: ["Cat Handling"],
    date: "2025-07-24",
    status: "Upcoming",
  },
  {
    volunteer: "Daniel Lee",
    event: "Clean Cages",
    location: "Secondary Shelter",
    urgency: "Low",
    skillsUsed: ["Cleaning"],
    date: "2025-07-22",
    status: "Upcoming",
  },
];
